# Generated by Django 6.1.1 on 2026-09-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
